version: "3.9"
#УБРАТЬ ПОРТЫ ТОРЧАЩИЕ НА РУЖУ НА ПРОДЕ
services:
  postgres:
    image: postgres:16-alpine
    container_name: yam-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: yam
      POSTGRES_PASSWORD: yam_secret
      POSTGRES_DB: yam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: yam-redis
    restart: unless-stopped
    command: redis-server --requirepass redis_secret

  mailhog:
    image: mailhog/mailhog
    container_name: yam-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  backend:
    build: ./backend
    container_name: yam-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.docker
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - ./backend:/app
    command: sh -c "npx prisma generate && npm run start:dev"

  frontend:
    build: ./frontend
    container_name: yam-frontend
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    container_name: yam-nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
